//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ покуп.
    /// </summary>
    // *** Start programmer edit section *** (ЗаказПокуп CustomAttributes)

    // *** End programmer edit section *** (ЗаказПокуп CustomAttributes)
    [AutoAltered()]
    [Caption("Заказ покуп")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказПокупE", new string[] {
            "ДатаОкончания as \'Дата окончания\'",
            "ДатаНачала as \'Дата начала\'",
            "СумВклНДС as \'Сум вкл НДС\'",
            "СостОтгруз as \'Сост отгруз\'",
            "СостОплат as \'Сост оплат\'",
            "СуммВклНДС as \'Сумм вкл НДС\'",
            "Организации as \'Организации\'",
            "Организации.Организация as \'Организация\'",
            "Контрагенты as \'Контрагенты\'",
            "Контрагенты.Контрагент as \'Контрагент\'",
            "Подразеления as \'Подразеления\'",
            "Подразеления.Подразделение as \'Подразделение\'",
            "Склады as \'Склады\'",
            "Склады.Склад as \'Склад\'"}, Hidden=new string[] {
            "Организации.Организация",
            "Контрагенты.Контрагент",
            "Подразеления.Подразделение",
            "Склады.Склад"})]
    [AssociatedDetailViewAttribute("ЗаказПокупE", "ТЧТоварИУслуг", "ТЧТоварИУслугE", true, "", "Т ч товар и услуг", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаказПокупE", "Организации", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Организация")]
    [MasterViewDefineAttribute("ЗаказПокупE", "Контрагенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Контрагент")]
    [MasterViewDefineAttribute("ЗаказПокупE", "Подразеления", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Подразделение")]
    [MasterViewDefineAttribute("ЗаказПокупE", "Склады", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Склад")]
    [View("ЗаказПокупL", new string[] {
            "ДатаОкончания as \'Дата окончания\'",
            "ДатаНачала as \'Дата начала\'",
            "СумВклНДС as \'Сум вкл НДС\'",
            "СостОтгруз as \'Сост отгруз\'",
            "СостОплат as \'Сост оплат\'",
            "СуммВклНДС as \'Сумм вкл НДС\'",
            "Организации.Организация as \'Организация\'",
            "Контрагенты.Контрагент as \'Контрагент\'",
            "Подразеления.Подразделение as \'Подразделение\'",
            "Склады.Склад as \'Склад\'"})]
    public class ЗаказПокуп : IIS.5.ОстатНаСклад
    {
        
        private int fСумВклНДС;
        
        private IIS.5.Контрагенты fКонтрагенты;
        
        private IIS.5.Подразеления fПодразеления;
        
        // *** Start programmer edit section *** (ЗаказПокуп CustomMembers)

        // *** End programmer edit section *** (ЗаказПокуп CustomMembers)

        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПокуп.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (ЗаказПокуп.ДатаНачала CustomAttributes)
        public override System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПокуп.ДатаНачала Get start)

                // *** End programmer edit section *** (ЗаказПокуп.ДатаНачала Get start)
                System.DateTime result = base.ДатаНачала;
                // *** Start programmer edit section *** (ЗаказПокуп.ДатаНачала Get end)

                // *** End programmer edit section *** (ЗаказПокуп.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПокуп.ДатаНачала Set start)

                // *** End programmer edit section *** (ЗаказПокуп.ДатаНачала Set start)
                base.ДатаНачала = value;
                // *** Start programmer edit section *** (ЗаказПокуп.ДатаНачала Set end)

                // *** End programmer edit section *** (ЗаказПокуп.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончания.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПокуп.ДатаОкончания CustomAttributes)

        // *** End programmer edit section *** (ЗаказПокуп.ДатаОкончания CustomAttributes)
        public override System.DateTime ДатаОкончания
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПокуп.ДатаОкончания Get start)

                // *** End programmer edit section *** (ЗаказПокуп.ДатаОкончания Get start)
                System.DateTime result = base.ДатаОкончания;
                // *** Start programmer edit section *** (ЗаказПокуп.ДатаОкончания Get end)

                // *** End programmer edit section *** (ЗаказПокуп.ДатаОкончания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПокуп.ДатаОкончания Set start)

                // *** End programmer edit section *** (ЗаказПокуп.ДатаОкончания Set start)
                base.ДатаОкончания = value;
                // *** Start programmer edit section *** (ЗаказПокуп.ДатаОкончания Set end)

                // *** End programmer edit section *** (ЗаказПокуп.ДатаОкончания Set end)
            }
        }
        
        /// <summary>
        /// СостОплат.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПокуп.СостОплат CustomAttributes)

        // *** End programmer edit section *** (ЗаказПокуп.СостОплат CustomAttributes)
        public override IIS.5.СостОплаты СостОплат
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПокуп.СостОплат Get start)

                // *** End programmer edit section *** (ЗаказПокуп.СостОплат Get start)
                IIS.5.СостОплаты result = base.СостОплат;
                // *** Start programmer edit section *** (ЗаказПокуп.СостОплат Get end)

                // *** End programmer edit section *** (ЗаказПокуп.СостОплат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПокуп.СостОплат Set start)

                // *** End programmer edit section *** (ЗаказПокуп.СостОплат Set start)
                base.СостОплат = value;
                // *** Start programmer edit section *** (ЗаказПокуп.СостОплат Set end)

                // *** End programmer edit section *** (ЗаказПокуп.СостОплат Set end)
            }
        }
        
        /// <summary>
        /// СостОтгруз.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПокуп.СостОтгруз CustomAttributes)

        // *** End programmer edit section *** (ЗаказПокуп.СостОтгруз CustomAttributes)
        public override IIS.5.СостОгрузки СостОтгруз
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПокуп.СостОтгруз Get start)

                // *** End programmer edit section *** (ЗаказПокуп.СостОтгруз Get start)
                IIS.5.СостОгрузки result = base.СостОтгруз;
                // *** Start programmer edit section *** (ЗаказПокуп.СостОтгруз Get end)

                // *** End programmer edit section *** (ЗаказПокуп.СостОтгруз Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПокуп.СостОтгруз Set start)

                // *** End programmer edit section *** (ЗаказПокуп.СостОтгруз Set start)
                base.СостОтгруз = value;
                // *** Start programmer edit section *** (ЗаказПокуп.СостОтгруз Set end)

                // *** End programmer edit section *** (ЗаказПокуп.СостОтгруз Set end)
            }
        }
        
        /// <summary>
        /// СумВклНДС.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПокуп.СумВклНДС CustomAttributes)

        // *** End programmer edit section *** (ЗаказПокуп.СумВклНДС CustomAttributes)
        public virtual int СумВклНДС
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПокуп.СумВклНДС Get start)

                // *** End programmer edit section *** (ЗаказПокуп.СумВклНДС Get start)
                int result = this.fСумВклНДС;
                // *** Start programmer edit section *** (ЗаказПокуп.СумВклНДС Get end)

                // *** End programmer edit section *** (ЗаказПокуп.СумВклНДС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПокуп.СумВклНДС Set start)

                // *** End programmer edit section *** (ЗаказПокуп.СумВклНДС Set start)
                this.fСумВклНДС = value;
                // *** Start programmer edit section *** (ЗаказПокуп.СумВклНДС Set end)

                // *** End programmer edit section *** (ЗаказПокуп.СумВклНДС Set end)
            }
        }
        
        /// <summary>
        /// Заказ покуп.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПокуп.Контрагенты CustomAttributes)

        // *** End programmer edit section *** (ЗаказПокуп.Контрагенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Контрагенты"})]
        [NotNull()]
        public virtual IIS.5.Контрагенты Контрагенты
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПокуп.Контрагенты Get start)

                // *** End programmer edit section *** (ЗаказПокуп.Контрагенты Get start)
                IIS.5.Контрагенты result = this.fКонтрагенты;
                // *** Start programmer edit section *** (ЗаказПокуп.Контрагенты Get end)

                // *** End programmer edit section *** (ЗаказПокуп.Контрагенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПокуп.Контрагенты Set start)

                // *** End programmer edit section *** (ЗаказПокуп.Контрагенты Set start)
                this.fКонтрагенты = value;
                // *** Start programmer edit section *** (ЗаказПокуп.Контрагенты Set end)

                // *** End programmer edit section *** (ЗаказПокуп.Контрагенты Set end)
            }
        }
        
        /// <summary>
        /// Заказ покуп.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПокуп.Организации CustomAttributes)

        // *** End programmer edit section *** (ЗаказПокуп.Организации CustomAttributes)
        [TypeUsage(typeof(IIS.5.Организации))]
        [PropertyStorage(new string[] {
                "Организации"})]
        public override IIS.5.Организации Организации
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПокуп.Организации Get start)

                // *** End programmer edit section *** (ЗаказПокуп.Организации Get start)
                IIS.5.Организации result = ((IIS.5.Организации)(base.Организации));
                // *** Start programmer edit section *** (ЗаказПокуп.Организации Get end)

                // *** End programmer edit section *** (ЗаказПокуп.Организации Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПокуп.Организации Set start)

                // *** End programmer edit section *** (ЗаказПокуп.Организации Set start)
                base.Организации = ((IIS.5.Организации)(value));
                // *** Start programmer edit section *** (ЗаказПокуп.Организации Set end)

                // *** End programmer edit section *** (ЗаказПокуп.Организации Set end)
            }
        }
        
        /// <summary>
        /// Заказ покуп.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПокуп.Подразеления CustomAttributes)

        // *** End programmer edit section *** (ЗаказПокуп.Подразеления CustomAttributes)
        [PropertyStorage(new string[] {
                "Подразеления"})]
        [NotNull()]
        public virtual IIS.5.Подразеления Подразеления
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПокуп.Подразеления Get start)

                // *** End programmer edit section *** (ЗаказПокуп.Подразеления Get start)
                IIS.5.Подразеления result = this.fПодразеления;
                // *** Start programmer edit section *** (ЗаказПокуп.Подразеления Get end)

                // *** End programmer edit section *** (ЗаказПокуп.Подразеления Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПокуп.Подразеления Set start)

                // *** End programmer edit section *** (ЗаказПокуп.Подразеления Set start)
                this.fПодразеления = value;
                // *** Start programmer edit section *** (ЗаказПокуп.Подразеления Set end)

                // *** End programmer edit section *** (ЗаказПокуп.Подразеления Set end)
            }
        }
        
        /// <summary>
        /// Заказ покуп.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПокуп.Склады CustomAttributes)

        // *** End programmer edit section *** (ЗаказПокуп.Склады CustomAttributes)
        [TypeUsage(typeof(IIS.5.Склады))]
        [PropertyStorage(new string[] {
                "Склады"})]
        public override IIS.5.Склады Склады
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПокуп.Склады Get start)

                // *** End programmer edit section *** (ЗаказПокуп.Склады Get start)
                IIS.5.Склады result = ((IIS.5.Склады)(base.Склады));
                // *** Start programmer edit section *** (ЗаказПокуп.Склады Get end)

                // *** End programmer edit section *** (ЗаказПокуп.Склады Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПокуп.Склады Set start)

                // *** End programmer edit section *** (ЗаказПокуп.Склады Set start)
                base.Склады = ((IIS.5.Склады)(value));
                // *** Start programmer edit section *** (ЗаказПокуп.Склады Set end)

                // *** End programmer edit section *** (ЗаказПокуп.Склады Set end)
            }
        }
        
        /// <summary>
        /// Заказ покуп.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказПокуп.ТЧТоварИУслуг CustomAttributes)

        // *** End programmer edit section *** (ЗаказПокуп.ТЧТоварИУслуг CustomAttributes)
        public override IIS.5.DetailArrayOfТЧТоварИУслуг ТЧТоварИУслуг
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказПокуп.ТЧТоварИУслуг Get start)

                // *** End programmer edit section *** (ЗаказПокуп.ТЧТоварИУслуг Get start)
                IIS.5.DetailArrayOfТЧТоварИУслуг result = base.ТЧТоварИУслуг;
                // *** Start programmer edit section *** (ЗаказПокуп.ТЧТоварИУслуг Get end)

                // *** End programmer edit section *** (ЗаказПокуп.ТЧТоварИУслуг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказПокуп.ТЧТоварИУслуг Set start)

                // *** End programmer edit section *** (ЗаказПокуп.ТЧТоварИУслуг Set start)
                base.ТЧТоварИУслуг = value;
                // *** Start programmer edit section *** (ЗаказПокуп.ТЧТоварИУслуг Set end)

                // *** End programmer edit section *** (ЗаказПокуп.ТЧТоварИУслуг Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказПокупE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказПокупE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказПокупE", typeof(IIS.5.ЗаказПокуп));
                }
            }
            
            /// <summary>
            /// "ЗаказПокупL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказПокупL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказПокупL", typeof(IIS.5.ЗаказПокуп));
                }
            }
        }
    }
}
