//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Остат на склад.
    /// </summary>
    // *** Start programmer edit section *** (ОстатНаСклад CustomAttributes)

    // *** End programmer edit section *** (ОстатНаСклад CustomAttributes)
    [AutoAltered()]
    [Caption("Остат на склад")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОстатНаСкладE", new string[] {
            "СостОплат as \'Сост оплат\'",
            "СуммВклНДС as \'Сумм вкл НДС\'",
            "ДатаНачала as \'Дата начала\'",
            "СостОтгруз as \'Сост отгруз\'",
            "ДатаОкончания as \'Дата окончания\'",
            "Организации as \'Организации\'",
            "Организации.Организация as \'Организация\'",
            "Склады as \'Склады\'",
            "Склады.Склад as \'Склад\'"}, Hidden=new string[] {
            "Организации.Организация",
            "Склады.Склад"})]
    [AssociatedDetailViewAttribute("ОстатНаСкладE", "ТЧТоварИУслуг", "ТЧТоварИУслугE", true, "", "Т ч товар и услуг", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ОстатНаСкладE", "Организации", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Организация")]
    [MasterViewDefineAttribute("ОстатНаСкладE", "Склады", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Склад")]
    [View("ОстатНаСкладL", new string[] {
            "СостОплат as \'Сост оплат\'",
            "СуммВклНДС as \'Сумм вкл НДС\'",
            "ДатаНачала as \'Дата начала\'",
            "СостОтгруз as \'Сост отгруз\'",
            "ДатаОкончания as \'Дата окончания\'",
            "Организации.Организация as \'Организация\'",
            "Склады.Склад as \'Склад\'"})]
    public class ОстатНаСклад : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.5.СостОплаты fСостОплат;
        
        private int fСуммВклНДС;
        
        private System.DateTime fДатаНачала = System.DateTime.Now;
        
        private IIS.5.СостОгрузки fСостОтгруз;
        
        private System.DateTime fДатаОкончания;
        
        private IIS.5.Организации fОрганизации;
        
        private IIS.5.Склады fСклады;
        
        private IIS.5.DetailArrayOfТЧТоварИУслуг fТЧТоварИУслуг;
        
        // *** Start programmer edit section *** (ОстатНаСклад CustomMembers)

        // *** End programmer edit section *** (ОстатНаСклад CustomMembers)

        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (ОстатНаСклад.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (ОстатНаСклад.ДатаНачала CustomAttributes)
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (ОстатНаСклад.ДатаНачала Get start)

                // *** End programmer edit section *** (ОстатНаСклад.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (ОстатНаСклад.ДатаНачала Get end)

                // *** End programmer edit section *** (ОстатНаСклад.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОстатНаСклад.ДатаНачала Set start)

                // *** End programmer edit section *** (ОстатНаСклад.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (ОстатНаСклад.ДатаНачала Set end)

                // *** End programmer edit section *** (ОстатНаСклад.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончания.
        /// </summary>
        // *** Start programmer edit section *** (ОстатНаСклад.ДатаОкончания CustomAttributes)

        // *** End programmer edit section *** (ОстатНаСклад.ДатаОкончания CustomAttributes)
        public virtual System.DateTime ДатаОкончания
        {
            get
            {
                // *** Start programmer edit section *** (ОстатНаСклад.ДатаОкончания Get start)

                // *** End programmer edit section *** (ОстатНаСклад.ДатаОкончания Get start)
                System.DateTime result = this.fДатаОкончания;
                // *** Start programmer edit section *** (ОстатНаСклад.ДатаОкончания Get end)

                // *** End programmer edit section *** (ОстатНаСклад.ДатаОкончания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОстатНаСклад.ДатаОкончания Set start)

                // *** End programmer edit section *** (ОстатНаСклад.ДатаОкончания Set start)
                this.fДатаОкончания = value;
                // *** Start programmer edit section *** (ОстатНаСклад.ДатаОкончания Set end)

                // *** End programmer edit section *** (ОстатНаСклад.ДатаОкончания Set end)
            }
        }
        
        /// <summary>
        /// СостОплат.
        /// </summary>
        // *** Start programmer edit section *** (ОстатНаСклад.СостОплат CustomAttributes)

        // *** End programmer edit section *** (ОстатНаСклад.СостОплат CustomAttributes)
        public virtual IIS.5.СостОплаты СостОплат
        {
            get
            {
                // *** Start programmer edit section *** (ОстатНаСклад.СостОплат Get start)

                // *** End programmer edit section *** (ОстатНаСклад.СостОплат Get start)
                IIS.5.СостОплаты result = this.fСостОплат;
                // *** Start programmer edit section *** (ОстатНаСклад.СостОплат Get end)

                // *** End programmer edit section *** (ОстатНаСклад.СостОплат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОстатНаСклад.СостОплат Set start)

                // *** End programmer edit section *** (ОстатНаСклад.СостОплат Set start)
                this.fСостОплат = value;
                // *** Start programmer edit section *** (ОстатНаСклад.СостОплат Set end)

                // *** End programmer edit section *** (ОстатНаСклад.СостОплат Set end)
            }
        }
        
        /// <summary>
        /// СостОтгруз.
        /// </summary>
        // *** Start programmer edit section *** (ОстатНаСклад.СостОтгруз CustomAttributes)

        // *** End programmer edit section *** (ОстатНаСклад.СостОтгруз CustomAttributes)
        public virtual IIS.5.СостОгрузки СостОтгруз
        {
            get
            {
                // *** Start programmer edit section *** (ОстатНаСклад.СостОтгруз Get start)

                // *** End programmer edit section *** (ОстатНаСклад.СостОтгруз Get start)
                IIS.5.СостОгрузки result = this.fСостОтгруз;
                // *** Start programmer edit section *** (ОстатНаСклад.СостОтгруз Get end)

                // *** End programmer edit section *** (ОстатНаСклад.СостОтгруз Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОстатНаСклад.СостОтгруз Set start)

                // *** End programmer edit section *** (ОстатНаСклад.СостОтгруз Set start)
                this.fСостОтгруз = value;
                // *** Start programmer edit section *** (ОстатНаСклад.СостОтгруз Set end)

                // *** End programmer edit section *** (ОстатНаСклад.СостОтгруз Set end)
            }
        }
        
        /// <summary>
        /// СуммВклНДС.
        /// </summary>
        // *** Start programmer edit section *** (ОстатНаСклад.СуммВклНДС CustomAttributes)

        // *** End programmer edit section *** (ОстатНаСклад.СуммВклНДС CustomAttributes)
        public virtual int СуммВклНДС
        {
            get
            {
                // *** Start programmer edit section *** (ОстатНаСклад.СуммВклНДС Get start)

                // *** End programmer edit section *** (ОстатНаСклад.СуммВклНДС Get start)
                int result = this.fСуммВклНДС;
                // *** Start programmer edit section *** (ОстатНаСклад.СуммВклНДС Get end)

                // *** End programmer edit section *** (ОстатНаСклад.СуммВклНДС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОстатНаСклад.СуммВклНДС Set start)

                // *** End programmer edit section *** (ОстатНаСклад.СуммВклНДС Set start)
                this.fСуммВклНДС = value;
                // *** Start programmer edit section *** (ОстатНаСклад.СуммВклНДС Set end)

                // *** End programmer edit section *** (ОстатНаСклад.СуммВклНДС Set end)
            }
        }
        
        /// <summary>
        /// Остат на склад.
        /// </summary>
        // *** Start programmer edit section *** (ОстатНаСклад.Организации CustomAttributes)

        // *** End programmer edit section *** (ОстатНаСклад.Организации CustomAttributes)
        [PropertyStorage(new string[] {
                "Организации"})]
        [NotNull()]
        public virtual IIS.5.Организации Организации
        {
            get
            {
                // *** Start programmer edit section *** (ОстатНаСклад.Организации Get start)

                // *** End programmer edit section *** (ОстатНаСклад.Организации Get start)
                IIS.5.Организации result = this.fОрганизации;
                // *** Start programmer edit section *** (ОстатНаСклад.Организации Get end)

                // *** End programmer edit section *** (ОстатНаСклад.Организации Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОстатНаСклад.Организации Set start)

                // *** End programmer edit section *** (ОстатНаСклад.Организации Set start)
                this.fОрганизации = value;
                // *** Start programmer edit section *** (ОстатНаСклад.Организации Set end)

                // *** End programmer edit section *** (ОстатНаСклад.Организации Set end)
            }
        }
        
        /// <summary>
        /// Остат на склад.
        /// </summary>
        // *** Start programmer edit section *** (ОстатНаСклад.Склады CustomAttributes)

        // *** End programmer edit section *** (ОстатНаСклад.Склады CustomAttributes)
        [PropertyStorage(new string[] {
                "Склады"})]
        [NotNull()]
        public virtual IIS.5.Склады Склады
        {
            get
            {
                // *** Start programmer edit section *** (ОстатНаСклад.Склады Get start)

                // *** End programmer edit section *** (ОстатНаСклад.Склады Get start)
                IIS.5.Склады result = this.fСклады;
                // *** Start programmer edit section *** (ОстатНаСклад.Склады Get end)

                // *** End programmer edit section *** (ОстатНаСклад.Склады Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОстатНаСклад.Склады Set start)

                // *** End programmer edit section *** (ОстатНаСклад.Склады Set start)
                this.fСклады = value;
                // *** Start programmer edit section *** (ОстатНаСклад.Склады Set end)

                // *** End programmer edit section *** (ОстатНаСклад.Склады Set end)
            }
        }
        
        /// <summary>
        /// Остат на склад.
        /// </summary>
        // *** Start programmer edit section *** (ОстатНаСклад.ТЧТоварИУслуг CustomAttributes)

        // *** End programmer edit section *** (ОстатНаСклад.ТЧТоварИУслуг CustomAttributes)
        public virtual IIS.5.DetailArrayOfТЧТоварИУслуг ТЧТоварИУслуг
        {
            get
            {
                // *** Start programmer edit section *** (ОстатНаСклад.ТЧТоварИУслуг Get start)

                // *** End programmer edit section *** (ОстатНаСклад.ТЧТоварИУслуг Get start)
                if ((this.fТЧТоварИУслуг == null))
                {
                    this.fТЧТоварИУслуг = new IIS.5.DetailArrayOfТЧТоварИУслуг(this);
                }
                IIS.5.DetailArrayOfТЧТоварИУслуг result = this.fТЧТоварИУслуг;
                // *** Start programmer edit section *** (ОстатНаСклад.ТЧТоварИУслуг Get end)

                // *** End programmer edit section *** (ОстатНаСклад.ТЧТоварИУслуг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОстатНаСклад.ТЧТоварИУслуг Set start)

                // *** End programmer edit section *** (ОстатНаСклад.ТЧТоварИУслуг Set start)
                this.fТЧТоварИУслуг = value;
                // *** Start programmer edit section *** (ОстатНаСклад.ТЧТоварИУслуг Set end)

                // *** End programmer edit section *** (ОстатНаСклад.ТЧТоварИУслуг Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОстатНаСкладE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОстатНаСкладE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОстатНаСкладE", typeof(IIS.5.ОстатНаСклад));
                }
            }
            
            /// <summary>
            /// "ОстатНаСкладL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОстатНаСкладL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОстатНаСкладL", typeof(IIS.5.ОстатНаСклад));
                }
            }
        }
    }
}
