//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.5
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч товар и услуг.
    /// </summary>
    // *** Start programmer edit section *** (ТЧТоварИУслуг CustomAttributes)

    // *** End programmer edit section *** (ТЧТоварИУслуг CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч товар и услуг")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧТоварИУслугE", new string[] {
            "Сумма as \'Сумма\'",
            "СуммаНДС as \'Сумма НДС\'",
            "Количестов as \'Количестов\'",
            "Цена as \'Цена\'",
            "Номенклатуры as \'Номенклатуры\'",
            "Номенклатуры.Номенклатура as \'Номенклатура\'"}, Hidden=new string[] {
            "Номенклатуры.Номенклатура"})]
    [MasterViewDefineAttribute("ТЧТоварИУслугE", "Номенклатуры", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номенклатура")]
    public class ТЧТоварИУслуг : ICSSoft.STORMNET.DataObject
    {
        
        private int fСумма;
        
        private int fСуммаНДС;
        
        private int fКоличестов;
        
        private int fЦена;
        
        private IIS.5.Номенклатуры fНоменклатуры;
        
        private IIS.5.ОстатНаСклад fОстатНаСклад;
        
        // *** Start programmer edit section *** (ТЧТоварИУслуг CustomMembers)

        // *** End programmer edit section *** (ТЧТоварИУслуг CustomMembers)

        
        /// <summary>
        /// Количестов.
        /// </summary>
        // *** Start programmer edit section *** (ТЧТоварИУслуг.Количестов CustomAttributes)

        // *** End programmer edit section *** (ТЧТоварИУслуг.Количестов CustomAttributes)
        public virtual int Количестов
        {
            get
            {
                // *** Start programmer edit section *** (ТЧТоварИУслуг.Количестов Get start)

                // *** End programmer edit section *** (ТЧТоварИУслуг.Количестов Get start)
                int result = this.fКоличестов;
                // *** Start programmer edit section *** (ТЧТоварИУслуг.Количестов Get end)

                // *** End programmer edit section *** (ТЧТоварИУслуг.Количестов Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧТоварИУслуг.Количестов Set start)

                // *** End programmer edit section *** (ТЧТоварИУслуг.Количестов Set start)
                this.fКоличестов = value;
                // *** Start programmer edit section *** (ТЧТоварИУслуг.Количестов Set end)

                // *** End programmer edit section *** (ТЧТоварИУслуг.Количестов Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (ТЧТоварИУслуг.Сумма CustomAttributes)

        // *** End programmer edit section *** (ТЧТоварИУслуг.Сумма CustomAttributes)
        public virtual int Сумма
        {
            get
            {
                // *** Start programmer edit section *** (ТЧТоварИУслуг.Сумма Get start)

                // *** End programmer edit section *** (ТЧТоварИУслуг.Сумма Get start)
                int result = this.fСумма;
                // *** Start programmer edit section *** (ТЧТоварИУслуг.Сумма Get end)

                // *** End programmer edit section *** (ТЧТоварИУслуг.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧТоварИУслуг.Сумма Set start)

                // *** End programmer edit section *** (ТЧТоварИУслуг.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (ТЧТоварИУслуг.Сумма Set end)

                // *** End programmer edit section *** (ТЧТоварИУслуг.Сумма Set end)
            }
        }
        
        /// <summary>
        /// СуммаНДС.
        /// </summary>
        // *** Start programmer edit section *** (ТЧТоварИУслуг.СуммаНДС CustomAttributes)

        // *** End programmer edit section *** (ТЧТоварИУслуг.СуммаНДС CustomAttributes)
        public virtual int СуммаНДС
        {
            get
            {
                // *** Start programmer edit section *** (ТЧТоварИУслуг.СуммаНДС Get start)

                // *** End programmer edit section *** (ТЧТоварИУслуг.СуммаНДС Get start)
                int result = this.fСуммаНДС;
                // *** Start programmer edit section *** (ТЧТоварИУслуг.СуммаНДС Get end)

                // *** End programmer edit section *** (ТЧТоварИУслуг.СуммаНДС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧТоварИУслуг.СуммаНДС Set start)

                // *** End programmer edit section *** (ТЧТоварИУслуг.СуммаНДС Set start)
                this.fСуммаНДС = value;
                // *** Start programmer edit section *** (ТЧТоварИУслуг.СуммаНДС Set end)

                // *** End programmer edit section *** (ТЧТоварИУслуг.СуммаНДС Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (ТЧТоварИУслуг.Цена CustomAttributes)

        // *** End programmer edit section *** (ТЧТоварИУслуг.Цена CustomAttributes)
        public virtual int Цена
        {
            get
            {
                // *** Start programmer edit section *** (ТЧТоварИУслуг.Цена Get start)

                // *** End programmer edit section *** (ТЧТоварИУслуг.Цена Get start)
                int result = this.fЦена;
                // *** Start programmer edit section *** (ТЧТоварИУслуг.Цена Get end)

                // *** End programmer edit section *** (ТЧТоварИУслуг.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧТоварИУслуг.Цена Set start)

                // *** End programmer edit section *** (ТЧТоварИУслуг.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (ТЧТоварИУслуг.Цена Set end)

                // *** End programmer edit section *** (ТЧТоварИУслуг.Цена Set end)
            }
        }
        
        /// <summary>
        /// Т ч товар и услуг.
        /// </summary>
        // *** Start programmer edit section *** (ТЧТоварИУслуг.Номенклатуры CustomAttributes)

        // *** End programmer edit section *** (ТЧТоварИУслуг.Номенклатуры CustomAttributes)
        [PropertyStorage(new string[] {
                "Номенклатуры"})]
        [NotNull()]
        public virtual IIS.5.Номенклатуры Номенклатуры
        {
            get
            {
                // *** Start programmer edit section *** (ТЧТоварИУслуг.Номенклатуры Get start)

                // *** End programmer edit section *** (ТЧТоварИУслуг.Номенклатуры Get start)
                IIS.5.Номенклатуры result = this.fНоменклатуры;
                // *** Start programmer edit section *** (ТЧТоварИУслуг.Номенклатуры Get end)

                // *** End programmer edit section *** (ТЧТоварИУслуг.Номенклатуры Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧТоварИУслуг.Номенклатуры Set start)

                // *** End programmer edit section *** (ТЧТоварИУслуг.Номенклатуры Set start)
                this.fНоменклатуры = value;
                // *** Start programmer edit section *** (ТЧТоварИУслуг.Номенклатуры Set end)

                // *** End programmer edit section *** (ТЧТоварИУслуг.Номенклатуры Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.5.ОстатНаСклад.
        /// </summary>
        // *** Start programmer edit section *** (ТЧТоварИУслуг.ОстатНаСклад CustomAttributes)

        // *** End programmer edit section *** (ТЧТоварИУслуг.ОстатНаСклад CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage("ОстатНаСклад")]
        [TypeUsage(new string[] {
                "IIS.5.ЗаказПокуп",
                "IIS.5.ОстатНаСклад"})]
        public virtual IIS.5.ОстатНаСклад ОстатНаСклад
        {
            get
            {
                // *** Start programmer edit section *** (ТЧТоварИУслуг.ОстатНаСклад Get start)

                // *** End programmer edit section *** (ТЧТоварИУслуг.ОстатНаСклад Get start)
                IIS.5.ОстатНаСклад result = this.fОстатНаСклад;
                // *** Start programmer edit section *** (ТЧТоварИУслуг.ОстатНаСклад Get end)

                // *** End programmer edit section *** (ТЧТоварИУслуг.ОстатНаСклад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧТоварИУслуг.ОстатНаСклад Set start)

                // *** End programmer edit section *** (ТЧТоварИУслуг.ОстатНаСклад Set start)
                this.fОстатНаСклад = value;
                // *** Start programmer edit section *** (ТЧТоварИУслуг.ОстатНаСклад Set end)

                // *** End programmer edit section *** (ТЧТоварИУслуг.ОстатНаСклад Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧТоварИУслугE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧТоварИУслугE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧТоварИУслугE", typeof(IIS.5.ТЧТоварИУслуг));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧТоварИУслуг.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧТоварИУслуг CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧТоварИУслуг CustomAttributes)
    public class DetailArrayOfТЧТоварИУслуг : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.5.DetailArrayOfТЧТоварИУслуг members)

        // *** End programmer edit section *** (IIS.5.DetailArrayOfТЧТоварИУслуг members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧТоварИУслуг by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧТоварИУслуг.
        /// </summary>
        public DetailArrayOfТЧТоварИУслуг(IIS.5.ОстатНаСклад fОстатНаСклад) : 
                base(typeof(ТЧТоварИУслуг), ((ICSSoft.STORMNET.DataObject)(fОстатНаСклад)))
        {
        }
        
        public IIS.5.ТЧТоварИУслуг this[int index]
        {
            get
            {
                return ((IIS.5.ТЧТоварИУслуг)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.5.ТЧТоварИУслуг dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
